### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Tsukumo290** [Tsukumo290/furima-38322#21]
### フリマアプリのURL
　https://furima-38322.herokuapp.com/
### Basic認証のIDとパスワード
　id: admin, パスワード: 2222
### 出品者用のメールアドレスとパスワード
　メールアドレス: nobita@email, パスワード: nobita290
### 購入者用のメールアドレスとパスワード
　メールアドレス: test@email, パスワード: test290

**Comment by Tsukumo290** [comment]
すみません、タイトルと共に送ってしまいましたが、パスワード等もう一度同じものを貼らせてもらいます。
動作確認のほどお願いします。

Basic認証のIDとパスワード
　id: admin, パスワード: 2222

出品者用のメールアドレスとパスワード
　メールアドレス: nobita@email, パスワード: nobita290

購入者用のメールアドレスとパスワード
　メールアドレス: test@email, パスワード: test290

**Comment by motomuun** [comment]
@Tsukumo290 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品一覧表示機能の確認**

- [x] **商品が出品されていない状態では、ダミーの商品情報が表示されること**
こちらの確認のため、一度画像を含むデータを全てリセットした上で再提出をお願いいたします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Tsukumo290** [comment]
こちらの動作は問題なさそうです
リセットしましたが、うまく動作しますでしょうか？？
各パスワードとemailは変わりありません

**Comment by shodai-ito** [comment]
@Tsukumo290 さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
```
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
```
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
```
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。
```

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/7105

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題LGTM](https://user-images.githubusercontent.com/62537107/182056366-7c7f9a41-f741-4c11-b5b5-254a8abe94f4.png)
